# Generated by Django 2.0.4 on 2018-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpdriller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Katakana',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('katakana', models.CharField(max_length=6, verbose_name='Katakana')),
                ('romanji', models.CharField(max_length=6, verbose_name='Romanji')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('group', models.CharField(max_length=20, verbose_name='Group')),
                ('vocabulary', models.CharField(max_length=20, verbose_name='Vocabulary')),
                ('pronounciation', models.CharField(max_length=20, verbose_name='Pronounciation')),
                ('translation', models.CharField(max_length=20, verbose_name='Translation')),
            ],
        ),
    ]
