# Generated by Django 2.0.4 on 2018-05-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpdriller', '0003_vocabulary_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='pronounciation',
            field=models.CharField(max_length=20, null=True, verbose_name='Pronounciation'),
        ),
    ]
